using System.Text.Json.Serialization;
using LionFire.OpenCode.Serve.Models;
using LionFire.OpenCode.Serve.Models.Events;

namespace LionFire.OpenCode.Serve.Internal;

/// <summary>
/// Source-generated JSON serializer context for AOT compatibility and improved performance.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false,
    PropertyNameCaseInsensitive = true)]
// Sessions
[JsonSerializable(typeof(Session))]
[JsonSerializable(typeof(List<Session>))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(UpdateSessionRequest))]
[JsonSerializable(typeof(ForkSessionRequest))]
[JsonSerializable(typeof(RevertSessionRequest))]
[JsonSerializable(typeof(InitSessionRequest))]
[JsonSerializable(typeof(ExecuteCommandRequest))]
[JsonSerializable(typeof(ExecuteShellRequest))]
[JsonSerializable(typeof(SummarizeSessionRequest))]
[JsonSerializable(typeof(SessionStatus))]
[JsonSerializable(typeof(SessionStatusIdle))]
[JsonSerializable(typeof(SessionStatusRetry))]
[JsonSerializable(typeof(SessionStatusBusy))]
[JsonSerializable(typeof(SessionSummary))]
[JsonSerializable(typeof(SessionShare))]
[JsonSerializable(typeof(SessionTime))]
[JsonSerializable(typeof(SessionRevert))]
// Messages
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(List<Message>))]
[JsonSerializable(typeof(MessageWithParts))]
[JsonSerializable(typeof(List<MessageWithParts>))]
[JsonSerializable(typeof(SendMessageRequest))]
[JsonSerializable(typeof(ModelReference))]
[JsonSerializable(typeof(MessageTime))]
[JsonSerializable(typeof(TokenUsage))]
[JsonSerializable(typeof(CacheUsage))]
[JsonSerializable(typeof(MessagePath))]
[JsonSerializable(typeof(MessageError))]
[JsonSerializable(typeof(MessageModel))]
[JsonSerializable(typeof(UserMessageSummary))]
[JsonSerializable(typeof(UserMessage))]
[JsonSerializable(typeof(AssistantMessage))]
// Parts (simplified - Part and PartInput are now concrete with all fields)
[JsonSerializable(typeof(Part))]
[JsonSerializable(typeof(List<Part>))]
[JsonSerializable(typeof(PartInput))]
[JsonSerializable(typeof(List<PartInput>))]
[JsonSerializable(typeof(PartTime))]
// Files
[JsonSerializable(typeof(FileNode))]
[JsonSerializable(typeof(List<FileNode>))]
[JsonSerializable(typeof(FileContent))]
[JsonSerializable(typeof(FileDiff))]
[JsonSerializable(typeof(List<FileDiff>))]
[JsonSerializable(typeof(FileStatus))]
[JsonSerializable(typeof(Patch))]
[JsonSerializable(typeof(PatchHunk))]
[JsonSerializable(typeof(List<PatchHunk>))]
// Permissions
[JsonSerializable(typeof(Permission))]
[JsonSerializable(typeof(List<Permission>))]
[JsonSerializable(typeof(PermissionResponse))]
[JsonSerializable(typeof(PermissionTime))]
[JsonSerializable(typeof(PermissionPattern))]
[JsonSerializable(typeof(SinglePermissionPattern))]
[JsonSerializable(typeof(MultiplePermissionPattern))]
// PTY
[JsonSerializable(typeof(Pty))]
[JsonSerializable(typeof(List<Pty>))]
[JsonSerializable(typeof(CreatePtyRequest))]
[JsonSerializable(typeof(UpdatePtyRequest))]
[JsonSerializable(typeof(PtyStatus))]
// MCP
[JsonSerializable(typeof(McpStatus))]
[JsonSerializable(typeof(List<McpStatus>))]
[JsonSerializable(typeof(McpStatusConnected))]
[JsonSerializable(typeof(McpStatusDisabled))]
[JsonSerializable(typeof(McpStatusFailed))]
[JsonSerializable(typeof(McpStatusNeedsAuth))]
[JsonSerializable(typeof(McpStatusNeedsClientRegistration))]
[JsonSerializable(typeof(AddMcpServerRequest))]
[JsonSerializable(typeof(McpConfig))]
[JsonSerializable(typeof(McpLocalConfig))]
[JsonSerializable(typeof(McpRemoteConfig))]
[JsonSerializable(typeof(McpOAuthConfig))]
// Providers
[JsonSerializable(typeof(Provider))]
[JsonSerializable(typeof(List<Provider>))]
[JsonSerializable(typeof(ProviderListResponse))]
[JsonSerializable(typeof(ProviderConfig))]
[JsonSerializable(typeof(Dictionary<string, Model>))]
[JsonSerializable(typeof(Model))]
[JsonSerializable(typeof(List<Model>))]
[JsonSerializable(typeof(ModelCost))]
[JsonSerializable(typeof(ModelCacheCost))]
[JsonSerializable(typeof(ModelLimit))]
[JsonSerializable(typeof(ProviderAuth))]
[JsonSerializable(typeof(List<ProviderAuth>))]
[JsonSerializable(typeof(ProviderAuthMethod))]
[JsonSerializable(typeof(ProviderAuthMethodApiKey))]
[JsonSerializable(typeof(ProviderAuthMethodOAuth))]
// Other Models
[JsonSerializable(typeof(Project))]
[JsonSerializable(typeof(List<Project>))]
[JsonSerializable(typeof(ProjectTime))]
[JsonSerializable(typeof(Agent))]
[JsonSerializable(typeof(List<Agent>))]
[JsonSerializable(typeof(AgentConfig))]
[JsonSerializable(typeof(Command))]
[JsonSerializable(typeof(List<Command>))]
[JsonSerializable(typeof(Todo))]
[JsonSerializable(typeof(List<Todo>))]
[JsonSerializable(typeof(Symbol))]
[JsonSerializable(typeof(List<Symbol>))]
[JsonSerializable(typeof(VcsInfo))]
[JsonSerializable(typeof(PathInfo))]
[JsonSerializable(typeof(LspStatus))]
[JsonSerializable(typeof(LspServer))]
[JsonSerializable(typeof(List<LspServer>))]
[JsonSerializable(typeof(FormatterStatus))]
[JsonSerializable(typeof(FormatterInfo))]
[JsonSerializable(typeof(List<FormatterInfo>))]
[JsonSerializable(typeof(LionFire.OpenCode.Serve.Models.Range))]
// Configuration
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(Dictionary<string, bool>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
// Events - Base
[JsonSerializable(typeof(Event))]
[JsonSerializable(typeof(GlobalEvent))]
// Events - Server
[JsonSerializable(typeof(ServerInstanceDisposedEvent))]
[JsonSerializable(typeof(ServerInstanceDisposedProperties))]
[JsonSerializable(typeof(ServerConnectedEvent))]
[JsonSerializable(typeof(ServerConnectedProperties))]
// Events - Session
[JsonSerializable(typeof(SessionCreatedEvent))]
[JsonSerializable(typeof(SessionCreatedProperties))]
[JsonSerializable(typeof(SessionUpdatedEvent))]
[JsonSerializable(typeof(SessionUpdatedProperties))]
[JsonSerializable(typeof(SessionDeletedEvent))]
[JsonSerializable(typeof(SessionDeletedProperties))]
[JsonSerializable(typeof(SessionStatusEvent))]
[JsonSerializable(typeof(SessionStatusProperties))]
[JsonSerializable(typeof(SessionIdleEvent))]
[JsonSerializable(typeof(SessionIdleProperties))]
[JsonSerializable(typeof(SessionCompactedEvent))]
[JsonSerializable(typeof(SessionCompactedProperties))]
[JsonSerializable(typeof(SessionDiffEvent))]
[JsonSerializable(typeof(SessionDiffProperties))]
[JsonSerializable(typeof(SessionErrorEvent))]
[JsonSerializable(typeof(SessionErrorProperties))]
// Events - Message
[JsonSerializable(typeof(MessageUpdatedEvent))]
[JsonSerializable(typeof(MessageUpdatedProperties))]
[JsonSerializable(typeof(MessageInfo))]
[JsonSerializable(typeof(MessageRemovedEvent))]
[JsonSerializable(typeof(MessageRemovedProperties))]
[JsonSerializable(typeof(MessagePartUpdatedEvent))]
[JsonSerializable(typeof(MessagePartUpdatedProperties))]
[JsonSerializable(typeof(MessagePartRemovedEvent))]
[JsonSerializable(typeof(MessagePartRemovedProperties))]
// Events - Permission
[JsonSerializable(typeof(PermissionUpdatedEvent))]
[JsonSerializable(typeof(PermissionUpdatedProperties))]
[JsonSerializable(typeof(PermissionRepliedEvent))]
[JsonSerializable(typeof(PermissionRepliedProperties))]
// Events - File
[JsonSerializable(typeof(FileEditedEvent))]
[JsonSerializable(typeof(FileEditedProperties))]
[JsonSerializable(typeof(FileWatcherUpdatedEvent))]
[JsonSerializable(typeof(FileWatcherUpdatedProperties))]
// Events - Todo
[JsonSerializable(typeof(TodoUpdatedEvent))]
[JsonSerializable(typeof(TodoUpdatedProperties))]
// Events - PTY
[JsonSerializable(typeof(PtyCreatedEvent))]
[JsonSerializable(typeof(PtyCreatedProperties))]
[JsonSerializable(typeof(PtyUpdatedEvent))]
[JsonSerializable(typeof(PtyUpdatedProperties))]
[JsonSerializable(typeof(PtyExitedEvent))]
[JsonSerializable(typeof(PtyExitedProperties))]
[JsonSerializable(typeof(PtyDeletedEvent))]
[JsonSerializable(typeof(PtyDeletedProperties))]
// Events - LSP
[JsonSerializable(typeof(LspUpdatedEvent))]
[JsonSerializable(typeof(LspUpdatedProperties))]
[JsonSerializable(typeof(LspClientDiagnosticsEvent))]
[JsonSerializable(typeof(LspClientDiagnosticsProperties))]
// Events - Command
[JsonSerializable(typeof(CommandExecutedEvent))]
[JsonSerializable(typeof(CommandExecutedProperties))]
// Events - VCS
[JsonSerializable(typeof(VcsBranchUpdatedEvent))]
[JsonSerializable(typeof(VcsBranchUpdatedProperties))]
// Events - Installation
[JsonSerializable(typeof(InstallationUpdatedEvent))]
[JsonSerializable(typeof(InstallationUpdatedProperties))]
[JsonSerializable(typeof(InstallationUpdateAvailableEvent))]
[JsonSerializable(typeof(InstallationUpdateAvailableProperties))]
// Events - TUI
[JsonSerializable(typeof(TuiPromptAppendEvent))]
[JsonSerializable(typeof(TuiPromptAppendProperties))]
[JsonSerializable(typeof(TuiCommandExecuteEvent))]
[JsonSerializable(typeof(TuiCommandExecuteProperties))]
[JsonSerializable(typeof(TuiToastShowEvent))]
[JsonSerializable(typeof(TuiToastShowProperties))]
// Common types
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(object))]
public partial class OpenCodeSerializerContext : JsonSerializerContext
{
}
